CREATE TABLE IF NOT EXISTS PERSONAL (
    id SERIAL PRIMARY KEY,
    organismo_nombre VARCHAR(200),
    anyo NUMERIC(6,2),
    mes VARCHAR(200),
    tipo_calificacionp VARCHAR(200),
    tipo_cargo VARCHAR(200),
    remuneracionbruta_mensual NUMERIC(12),
    remuliquida_mensual NUMERIC(12),
    base VARCHAR(200),
    tipo_pago VARCHAR(200),
    num_cuotas NUMERIC(6,2),
    nombrecompleto_x VARCHAR(200),
    rut VARCHAR(200),
    nombreencontrado VARCHAR(200),
    cantidad_pagos_mes NUMERIC(6,2),
    detalle_base_pagos_mes NUMERIC(6,2),
    tipo_contrato_distintos NUMERIC(6,2),
    homologado VARCHAR(200),
    homologado_2 VARCHAR(200),
    key VARCHAR(200),
    metodo VARCHAR(200)
);